variable "ENV" {}
variable "INSTANCE_TYPE" {}
variable "SPOT_INSTANCE_COUNT" {}
variable "OD_INSTANCE_COUNT" {}
variable "COMPONENT" {}
variable "WORKSTATION_IP" {}
variable "APP_PORT" {}
variable "APP_VERSION" {}
variable "APP_TYPE" {}
